const hint = [
  {
    name: "Klasa 1 - 3",
    quizzes: [
      {
        quiz: "Quiz 0",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 1",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 2",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 3",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 4",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 5",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 6",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 7",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 8",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 9",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
    ],
  },
  {
    name: "Klasa 4 - 8",
    quizzes: [
      {
        quiz: "Quiz 0",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 1",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 2",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 3",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 4",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 5",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 6",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 7",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 8",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 9",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
    ],
  },
  {
    name: "Tech - Liceum",
    quizzes: [
      {
        quiz: "Quiz 0",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 1",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 2",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 3",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 4",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 5",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 6",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 7",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 8",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
      {
        quiz: "Quiz 9",
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
      },
    ],
  },
];

export default hint;
