const category = [
  {
    name: "Klasa 1 - 3",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        performed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
    ],
  },
  {
    name: "Klasa 4 - 8",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        performed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
    ],
  },
  {
    name: "Tech - Liceum",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        performed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        performed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: false,
        0: { hint: true },
        1: { hint: true },
        2: { hint: true },
        3: { hint: true },
        usedTime: 0,
        grade: 0,
      },
    ],
  },
];

export default category;
