const category = [
  {
    name: "Klasa 1 - 3",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
    ],
  },
  {
    name: "Klasa 4 - 8",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
    ],
  },
  {
    name: "Tech - Liceum",
    quizzes: [
      {
        quiz: "Quiz 0",
        passed: false,
        locked: false,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 1",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 2",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 3",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 4",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 5",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 6",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 7",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 8",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
      {
        quiz: "Quiz 9",
        passed: false,
        locked: true,
        finalScore: 0,
        isFirstOpen: true,
      },
    ],
  },
];

export default category;
